jobs:
- job: build
  pool:
    vmImage: 'ubuntu-16.04'
  steps:
  - script: |
      sudo apt-get install -y xorriso systemd-container genisoimage
    displayName: Install dependencies

  - script: |
      make rootfs
    displayName: Download and extract Ubuntu installer

  - script: |
      sudo make prepare
    displayName: Prepare RootFS

  - script: |
      sudo make apply-role
    displayName: Apply device-farm-node role

  - script: |
      sudo systemd-nspawn -D squashfs-root/ /root/scripts/cleanup.sh
      sudo rm squashfs-root/root/scripts/
    displayName: Cleanup

  - script: |
      sudo chmod +w extract/casper/filesystem.manifest
      sudo systemd-nspawn -D squashfs-root dpkg-query -W --showformat='${Package} ${Version}\n' | sudo tee upstream/casper/filesystem.manifest
    displayName: Update the manifest

  - script: |
      sudo mksquashfs squashfs-root upstream/casper/filesystem.squashfs -b 1048576
      printf $(sudo du -sx --block-size=1 edit | cut -f1) | sudo tee upstream/casper/filesystem.size
      rm upstream/md5sum.txt
      (cd upstream && find -type f -print0 | sudo xargs -0 md5sum | grep -v isolinux/boot.cat) | sudo tee upstream/md5sum.txt
    displayName: Compress the filesystem

  - script: |
      mkdir -p $BUILD_ARTIFACTSTAGINGDIRECTORY/iso
      sudo genisoimage -D -r -V "$IMAGE_NAME" -cache-inodes -J -l -b isolinux/isolinux.bin -c isolinux/boot.cat -no-emul-boot -boot-load-size 4 -boot-info-table -o $BUILD_ARTIFACTSTAGINGDIRECTORY/iso/quamotion-device-node.iso upstream/
    displayName: Create the iso image

  - task: PublishBuildArtifacts@1
    inputs:
      pathtoPublish: '$(Build.ArtifactStagingDirectory)/iso'
      artifactName: 'iso'
      publishLocation: 'Container'
    displayName: Publish
