jobs:
- job: build
  pool:
    vmImage: 'ubuntu-16.04'
  steps:
  - script: |
      sudo apt-get install -y xorriso systemd-container genisoimage isolinux
    displayName: Install dependencies

  - script: |
      make rootfs
    displayName: Download and extract Ubuntu installer

  - script: |
      sudo make prepare
    displayName: Prepare RootFS

  - script: |
      sudo make apply-role
    displayName: Apply device-farm-node role

  - script: |
      sudo make iso
      mkdir -p ${BUILD_ARTIFACTSTAGINGDIRECTORY}/iso/
      mkdir -p ${BUILD_ARTIFACTSTAGINGDIRECTORY}/rootfs/
      cp quamotion-device-node.iso ${BUILD_ARTIFACTSTAGINGDIRECTORY}/iso/
      cp upstream/casper/installer.squashfs ${BUILD_ARTIFACTSTAGINGDIRECTORY}/rootfs/
    displayName: Create the iso image

  - task: PublishBuildArtifacts@1
    inputs:
      pathtoPublish: '$(Build.ArtifactStagingDirectory)/iso'
      artifactName: 'iso'
      publishLocation: 'Container'
    displayName: Publish

  - task: PublishBuildArtifacts@1
    inputs:
      pathtoPublish: '$(Build.ArtifactStagingDirectory)/rootfs'
      artifactName: 'rootfs'
      publishLocation: 'Container'
    displayName: Publish
